-- Auto-generated by RSDWCustomBuilds Write-F7Manifest.ps1
-- native_placement=true: OnPieceSelected(custom DA); visuals from pak BP. catalogue_index = AllPiecesInCatalogue slot at build time.
return {
    version = 1,
    pak = "RSDragonwilds-Z_RSDWCustomBuilds_P",
    pieces = {
        {
            id = "ChurchWall",
            display_name = "Church Brick Wall",
            donor = "wall_large",
            persistence_id = "RSDWBuilds_ChurchWall_v1",
            da_path = "/Game/Gameplay/BaseBuilding_New/BuildingPieces/RSDWBuilds/ChurchWall/DA_ChurchWall.DA_ChurchWall",
            bp_path = "/Game/RSDWBuilds/ChurchWall/BP_ChurchWall.BP_ChurchWall_C",
            mesh_path = "/Game/RSDWBuilds/ChurchWall/SM_ChurchWall.SM_ChurchWall",
            icon_path = "/Game/RSDWBuilds/ChurchWall/T_Icon_ChurchWall.T_Icon_ChurchWall",
            runtime_material = false,
            pak_first = true,
            native_placement = true,
            catalogue_index = 755,
        },
        {
            id = "SpikeWall",
            display_name = "Spike Wall",
            donor = "wall_large",
            persistence_id = "RSDWBuilds_SpikeWall_v1",
            da_path = "/Game/Gameplay/BaseBuilding_New/BuildingPieces/RSDWBuilds/SpikeWall/DA_SpikeWall.DA_SpikeWall",
            bp_path = "/Game/RSDWBuilds/SpikeWall/BP_SpikeWall.BP_SpikeWall_C",
            mesh_path = "/Game/RSDWBuilds/SpikeWall/SM_SpikeWall.SM_SpikeWall",
            icon_path = "/Game/RSDWBuilds/SpikeWall/T_Icon_SpikeWall.T_Icon_SpikeWall",
            runtime_material = false,
            pak_first = true,
            native_placement = true,
            catalogue_index = 756,
        }
    },
}
