param(
    [string]$ConfigPath,
    [string]$PieceName = "",
    [string]$DisplayName = "",
    [string]$Donor = "foundation_large",
    [switch]$Interactive
)

$ErrorActionPreference = "Stop"
if ($ConfigPath) {
    $cfg = & "$PSScriptRoot\Read-Config.ps1" -ConfigPath $ConfigPath
} else {
    $cfg = & "$PSScriptRoot\Read-Config.ps1"
}

function ConvertTo-PieceId {
    param([string]$Raw)
    $s = $Raw.Trim()
    if ($s -match '\s') {
        $parts = $s -split '\s+' | Where-Object { $_ -ne "" }
        $s = ($parts | ForEach-Object {
            if ($_.Length -eq 0) { return "" }
            $_.Substring(0, 1).ToUpper() + $_.Substring(1).ToLower()
        }) -join ""
    }
    return $s
}

function Get-MenuCategoryForDonor {
    param([string]$DonorKey)
    switch ($DonorKey) {
        "foundation_large" { return "foundations" }
        "foundation_med" { return "foundations" }
        "wall_large" { return "walls" }
        "floor_large" { return "floors" }
        "roof_large" { return "roofs" }
        default { return "foundations" }
    }
}

function Read-PieceNameInteractive {
    while ($true) {
        $raw = Read-Host "Piece name (PascalCase, e.g. StoneWall)"
        if ([string]::IsNullOrWhiteSpace($raw)) {
            Write-Host "Name cannot be empty." -ForegroundColor Yellow
            continue
        }
        $id = ConvertTo-PieceId $raw
        if ($id -notmatch '^[A-Za-z][A-Za-z0-9]*$') {
            Write-Host "Invalid name '$id'. Use letters and numbers only." -ForegroundColor Yellow
            continue
        }
        if ($raw -match '\s' -and $id -ne $raw) {
            Write-Host "Using piece id: $id"
        }
        return $id
    }
}

function Read-DisplayNameInteractive {
    param([string]$Default)
    $raw = Read-Host "Display name in build menu [$Default]"
    if ([string]::IsNullOrWhiteSpace($raw)) { return $Default }
    return $raw.Trim()
}

function Read-DonorInteractive {
    $options = @(
        @{ Key = "1"; Value = "foundation_large"; Label = "Large foundation (300x300 cm)" },
        @{ Key = "2"; Value = "foundation_med"; Label = "Medium foundation" },
        @{ Key = "3"; Value = "wall_large"; Label = "Wall panel" },
        @{ Key = "4"; Value = "floor_large"; Label = "Floor tile" },
        @{ Key = "5"; Value = "roof_large"; Label = "Roof piece (30 deg shallow roof snaps)" }
    )
    Write-Host ""
    Write-Host "Donor type (snap / placement behaviour):"
    foreach ($o in $options) {
        Write-Host "  $($o.Key)) $($o.Label)"
    }
    while ($true) {
        $pick = Read-Host "Choose [1]"
        if ([string]::IsNullOrWhiteSpace($pick)) { $pick = "1" }
        $hit = $options | Where-Object { $_.Key -eq $pick } | Select-Object -First 1
        if ($hit) { return $hit.Value }
        Write-Host "Enter 1-5." -ForegroundColor Yellow
    }
}

if ($Interactive -or [string]::IsNullOrWhiteSpace($PieceName)) {
    Write-Host ""
    Write-Host "=== RSDW Custom Builds - New Piece ==="
    Write-Host ""
    $PieceName = Read-PieceNameInteractive
    $autoDisplay = ($PieceName -creplace '([a-z])([A-Z])', '$1 $2')
    $DisplayName = Read-DisplayNameInteractive -Default $autoDisplay
    $Donor = Read-DonorInteractive
}

if ($PieceName -notmatch '^[A-Za-z][A-Za-z0-9]*$') {
    throw "Invalid PieceName '$PieceName'. Use PascalCase letters/digits only (e.g. StoneWall)."
}

$validDonors = @("foundation_large", "foundation_med", "wall_large", "floor_large", "roof_large")
if ($validDonors -notcontains $Donor) {
    throw "Invalid donor '$Donor'. Use: $($validDonors -join ', ')"
}
if (-not $cfg.DonorMap -or -not $cfg.DonorMap.ContainsKey($Donor)) {
    throw "Donor '$Donor' is not configured in mod.config.ini [donors]. Run Setup or add the donor path."
}

if ([string]::IsNullOrWhiteSpace($DisplayName)) {
    $DisplayName = ($PieceName -creplace '([a-z])([A-Z])', '$1 $2')
}

$menuCategory = Get-MenuCategoryForDonor $Donor

$pieceDir = Join-Path $cfg.ContentRoot $PieceName
if (Test-Path $pieceDir) {
    throw "Folder already exists: $pieceDir"
}

New-Item -ItemType Directory -Force -Path $pieceDir | Out-Null

$ini = @"
[piece]
display_name = $DisplayName
donor = $Donor
persistence_id = auto
cost_wood = 0
menu_category = $menuCategory
catalogue_index = auto
native_placement = true

"@

$iniPath = Join-Path $pieceDir "piece.ini"
Set-Content -Path $iniPath -Value $ini -Encoding UTF8

if ($cfg.BuildsFolder -and -not [string]::IsNullOrWhiteSpace($cfg.BuildsFolder)) {
    $buildsDir = Join-Path $cfg.BuildsFolder $PieceName
    New-Item -ItemType Directory -Force -Path $buildsDir | Out-Null
    Copy-Item -LiteralPath $iniPath -Destination (Join-Path $buildsDir "piece.ini") -Force
}

$readme = @"
# $PieceName

Generated by New-Piece.bat

Next in Unreal (this folder):
  SM_$PieceName          <- static mesh (required)
  T_Icon_$PieceName      <- menu icon (optional; Build All uses donor icon if missing)
  MI_${PieceName}_*      <- material instances on mesh slots
  T_*                    <- textures for your MIs

Donor behaviour (auto from piece.ini):
  foundation_large -> BP_T1_Foundation_Large
  foundation_med   -> BP_T1_Foundation_Med
  wall_large       -> BP_T1_Wall_Large
  floor_large      -> BP_T1_Floor_Large
  roof_large       -> BP_T1_Roof_Large_Shallow

Then: Manager -> Build All   (or Tools\Build-All.bat)
BP/DA/catalogue are generated automatically - no manual UAssetGUI steps.
"@

Set-Content -Path (Join-Path $pieceDir "README.txt") -Value $readme -Encoding UTF8

Write-Host ""
Write-Host "Created piece: $PieceName"
Write-Host "  Folder:   $pieceDir"
Write-Host "  Config:   $iniPath"
Write-Host "  Display:  $DisplayName"
Write-Host "  Donor:    $Donor"
Write-Host "  Menu:     $menuCategory"
Write-Host ""
Write-Host "Next: open RSDWCustomBuilds.uproject and add SM_$PieceName in Content/RSDWBuilds/$PieceName/"
Write-Host "Then: Build All in the Manager"

return [PSCustomObject]@{
    Id          = $PieceName
    Folder      = $pieceDir
    DisplayName = $DisplayName
    Donor       = $Donor
    MenuCategory = $menuCategory
}
