param(
    [string]$ConfigPath,
    [object[]]$Pieces,
    [string]$BlankMenuRoot
)

$ErrorActionPreference = "Stop"
if ($ConfigPath) {
    $cfg = & "$PSScriptRoot\Read-Config.ps1" -ConfigPath $ConfigPath
} else {
    $cfg = & "$PSScriptRoot\Read-Config.ps1"
}

if (-not $BlankMenuRoot) {
    $kitBlank = Join-Path $cfg.ProjectRoot "RSDWBlankMenu"
    $siblingBlank = Join-Path (Split-Path $cfg.ProjectRoot -Parent) "RSDWBlankMenu"
    if (Test-Path -LiteralPath $kitBlank) {
        $BlankMenuRoot = $kitBlank
    } else {
        $BlankMenuRoot = $siblingBlank
    }
}
if (-not (Test-Path -LiteralPath $BlankMenuRoot)) {
    Write-Host "Write-F7Manifest: skip (no RSDWBlankMenu at $BlankMenuRoot)"
    return
}

function Get-DonorIconPath {
    param([string]$DonorKey, $DonorMap, [string]$ArchiveRoot)
    if (-not $DonorKey -or -not $DonorMap -or -not $ArchiveRoot) { return $null }
    $rel = $null
    if ($DonorMap -is [hashtable] -and $DonorMap.ContainsKey($DonorKey)) {
        $rel = $DonorMap[$DonorKey]
    }
    if (-not $rel) { return $null }
    $jsonPath = Join-Path $ArchiveRoot $rel
    if (-not (Test-Path -LiteralPath $jsonPath)) { return $null }
    $arr = Get-Content -LiteralPath $jsonPath -Raw | ConvertFrom-Json
    $entry = if ($arr -is [System.Array]) { $arr[0] } else { $arr }
    $path = [string]$entry.Properties.DisplayIcon.AssetPathName
    if ([string]::IsNullOrWhiteSpace($path)) { return $null }
    return $path
}

if (-not $Pieces -or $Pieces.Count -eq 0) {
    $Pieces = & "$PSScriptRoot\Scan-Pieces.ps1" -ConfigPath $cfg.ConfigPath
}

$f7Pieces = @()
foreach ($p in $Pieces) {
    if (-not $p.HasStaticMesh) { continue }

    $donor = [string]$p.Donor
    $prefix = $p.GamePathPrefix
    $daScanRoot = "/Game/Gameplay/BaseBuilding_New/BuildingPieces/$($cfg.CookFolder)/$($p.Id)"
    $meshPath = "$prefix/SM_$($p.Id).SM_$($p.Id)"
    $daPath = "$daScanRoot/DA_$($p.Id).DA_$($p.Id)"
    $bpPath = "$prefix/BP_$($p.Id).BP_$($p.Id)_C"
    $iconPath = "$prefix/T_Icon_$($p.Id).T_Icon_$($p.Id)"
    $iconUasset = Join-Path $cfg.ProjectRoot "Content\$($cfg.CookFolder)\$($p.Id)\T_Icon_$($p.Id).uasset"
    if (-not (Test-Path -LiteralPath $iconUasset)) {
        $donorIcon = Get-DonorIconPath $donor $cfg.DonorMap $cfg.ArchiveJsonRoot
        if ($donorIcon) { $iconPath = $donorIcon }
    }

    $pieceDir = Join-Path $cfg.ProjectRoot "Content\$($cfg.CookFolder)\$($p.Id)"
    $hasMi = $false
    if (Test-Path -LiteralPath $pieceDir) {
        $hasMi = @(Get-ChildItem -LiteralPath $pieceDir -Filter "MI_*.uasset" -ErrorAction SilentlyContinue).Count -gt 0
    }
    $runtimeMaterial = -not $hasMi

    $entry = @{
        id               = $p.Id
        display_name     = $p.DisplayName
        donor            = $donor
        persistence_id   = [string]$p.PersistenceId
        da_path          = $daPath
        bp_path          = $bpPath
        mesh_path        = $meshPath
        icon_path        = $iconPath
        runtime_material = $runtimeMaterial
        pak_first        = $true
        native_placement = [bool]$p.NativePlacement
        catalogue_index  = $p.CatalogueIndex
    }

    if ($runtimeMaterial) {
        $baseUasset = Join-Path $pieceDir "T_Walls.uasset"
        if (Test-Path -LiteralPath $baseUasset) {
            $entry.base_tex = "$prefix/T_Walls.T_Walls"
            $entry.norm_tex = "$prefix/T_Walls_N.T_Walls_N"
        }
    }

    $f7Pieces += $entry
    $matNote = if ($runtimeMaterial) { "runtime textures" } else { "baked MI on SM" }
    $modeNote = if ($p.NativePlacement) { "native" } else { "hybrid" }
    Write-Host "  F7 $($p.Id): $modeNote da=$daPath ($matNote)"
}

$luaLines = @(
    "-- Auto-generated by RSDWCustomBuilds Write-F7Manifest.ps1",
    "-- native_placement=true: OnPieceSelected(custom DA); visuals from pak BP. catalogue_index = AllPiecesInCatalogue slot at build time.",
    "return {",
    "    version = 1,",
    "    pak = `"$($cfg.PakBasename)`",",
    "    pieces = {"
)

for ($i = 0; $i -lt $f7Pieces.Count; $i++) {
    $e = $f7Pieces[$i]
    $comma = if ($i -lt ($f7Pieces.Count - 1)) { "," } else { "" }
    $display = ([string]$e.display_name).Replace('"', '\"')
    $rtMat = if ($e.runtime_material) { "true" } else { "false" }
    $native = if ($e.native_placement) { "true" } else { "false" }
    $luaLines += "        {"
    $luaLines += "            id = `"$($e.id)`","
    $luaLines += "            display_name = `"$display`","
    $luaLines += "            donor = `"$($e.donor)`","
    $luaLines += "            persistence_id = `"$($e.persistence_id)`","
    $luaLines += "            da_path = `"$($e.da_path)`","
    $luaLines += "            bp_path = `"$($e.bp_path)`","
    $luaLines += "            mesh_path = `"$($e.mesh_path)`","
    $luaLines += "            icon_path = `"$($e.icon_path)`","
    $luaLines += "            runtime_material = $rtMat,"
    $luaLines += "            pak_first = true,"
    $luaLines += "            native_placement = $native,"
    $luaLines += "            catalogue_index = $($e.catalogue_index),"
    if ($e.base_tex) {
        $luaLines += "            base_tex = `"$($e.base_tex)`","
        $luaLines += "            norm_tex = `"$($e.norm_tex)`","
    }
    $luaLines += "        }$comma"
}

$luaLines += "    },"
$luaLines += "}"

$outPath = Join-Path $BlankMenuRoot "Scripts\pieces_data.lua"
Set-Content -Path $outPath -Value ($luaLines -join "`n") -Encoding UTF8
Write-Host "Wrote F7 manifest: $outPath ($($f7Pieces.Count) piece(s))"

return $f7Pieces
